"""
NEXUS-II — config package
Re-exports the complete settings surface so callers can do:

    from config import LLM_MAIN, IST, TRADING_MODE
"""
from config.settings import (
    TRADING_MODE,
    IST,
    CLAUDE_API_KEY,
    DHAN_ACCESS_TOKEN,
    DHAN_CLIENT_ID,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY,
    ALPHA_VANTAGE_KEY,
    FRED_API_KEY,
    FINNHUB_API_KEY,
    LLM_MAIN,
    LLM_FAST,
    MARKET_OPEN,
    MARKET_CLOSE,
    INTRADAY_SQUAREOFF,
    PRE_MARKET_START,
    CALIBRATION_TTL_MARKET_HOURS,
    CALIBRATION_TTL_OFF_HOURS,
    OPTIONS_CHAIN_RATE_LIMIT_SECONDS,
    LOG_LEVEL,
)

from config.universe import UNIVERSE, MARKET_UNIVERSES
from config.strategy_params import STRATEGY_PARAMS

__all__ = [
    "TRADING_MODE", "IST",
    "CLAUDE_API_KEY", "DHAN_ACCESS_TOKEN", "DHAN_CLIENT_ID",
    "TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID",
    "SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY",
    "ALPHA_VANTAGE_KEY", "FRED_API_KEY", "FINNHUB_API_KEY",
    "LLM_MAIN", "LLM_FAST",
    "MARKET_OPEN", "MARKET_CLOSE", "INTRADAY_SQUAREOFF", "PRE_MARKET_START",
    "CALIBRATION_TTL_MARKET_HOURS", "CALIBRATION_TTL_OFF_HOURS",
    "OPTIONS_CHAIN_RATE_LIMIT_SECONDS", "LOG_LEVEL",
    "UNIVERSE", "MARKET_UNIVERSES", "STRATEGY_PARAMS",
]
